DELETE FROM content;
DELETE FROM gallery;
DELETE FROM brands;
INSERT INTO content (key, value) VALUES ('meta', '{"title":"Discover With Leigh | Photographer & Digital Marketing Specialist","description":"Professional photography, video creation, social media management and influencer campaigns in Cape Town. Let’s bring your brand to life through stunning visuals and compelling marketing.","url":"https://discoverwithleigh.co.za"}');
INSERT INTO content (key, value) VALUES ('hero', '{"title":"Discover With Leigh","subtitle":"Professional Photographer & Digital Marketing Specialist"}');
INSERT INTO content (key, value) VALUES ('about', '{"eyebrow":"About me","heading":"I bring your brand to life through stunning visuals and compelling marketing.","body":["My expertise in professional photography, marketing video content, social media management, and influencer campaigns ensures that I create authentic content that truly resonates with your audience. My unparalleled skills and unwavering dedication to excellence have built a loyal community that trusts my work. Let’s collaborate to elevate your brand and achieve extraordinary success together.","Ready to take your brand to the next level? Contact me today to get started on creating exceptional content that captivates and converts. Let’s make your vision a reality!"],"cta":"Get started here"}');
INSERT INTO content (key, value) VALUES ('services', '["Professional Photography","Video Creation","Social Media Management","Influencer Campaigns"]');
INSERT INTO content (key, value) VALUES ('photography', '{"eyebrow":"Capturing moments & memories","heading":"Professional Photography","body":"Photography is at the heart of everything I do. It’s more than just my passion — it’s the foundation of my work and what drives me to excel in every project. I specialise in Product, Lifestyle, Music, Portrait, Wedding, and Property Photography, delivering high-quality images tailored to your needs. With a focus on vibrant, emotional, and warm visuals, I approach every shoot with creativity and dedication, ensuring that your vision is brought to life with precision and care.","categories":["Portraits","Weddings","Property","Live Music","Product","Lifestyle"],"cta":{"line":"Let’s make your ideas & memories come to life!","label":"Get started here"}}');
INSERT INTO content (key, value) VALUES ('video', '{"eyebrow":"Elevate your brand","heading":"Marketing Video Creation","body":["Creating stunning content for brands and agencies, and making high quality content accessible is my absolute passion. With over a decade of experience, we specialise in crafting beautiful video and still content that brings your brand to life.","Since 2013, we’ve been perfecting the art of capturing everything our clients envision. Services include photography, videography, and copywriting. Whether you’re a large agency or a small business, we create content that truly represents your brand, making it shine in a competitive market."],"tiktokIds":["7222594449979804933","7293572260181429509"],"cta":{"line":"Ready to create some amazing video content?","label":"Get started here"}}');
INSERT INTO content (key, value) VALUES ('marketing', '{"eyebrow":"Strategic content for your brand","heading":"Social Media Management","body":["My social media management service is crafted to not only help you build but also sustain a powerful and lasting online presence. I take a strategic and customised approach to every client’s social media, carefully crafting content that is engaging, relevant, and tailored to resonate with your audience.","Whether it’s curating daily posts that keep your brand top of mind, interacting with your audience through comments and messages, or running data-driven campaigns that deliver measurable results, I focus on strategies that keep your brand active, relevant, and thriving in an ever-evolving digital space."],"processTitle":"The Discovery Process","process":[{"name":"Strategy","text":"Power up your business with a dynamic social media strategy to conquer your business goals and skyrocket your brand’s online presence."},{"name":"Creation","text":"Create brand-aligned content that captivates your audience, forming unbreakable brand loyalty. Organise this content into a strategic calendar for maximum success."},{"name":"Posting & Management","text":"Energise your online presence: deliver impactful content, vigilantly monitor responses, and actively engage with and manage your growing community."},{"name":"Success","text":"Unleash the power of data. We rigorously analyse performance metrics, decipher audience behaviours, and leverage insights to sharpen strategies and supercharge future content optimisation."}],"cta":{"line":"Let’s create a powerful social media strategy","label":"Get started here"}}');
INSERT INTO content (key, value) VALUES ('influencer', '{"eyebrow":"Amplify your brand’s reach","heading":"Influencer Campaigns","body":["Unlock your brand’s potential by partnering with me for your next influencer campaign! From unboxings and product reviews to customer experience videos, my content authentically connects with a loyal community that trusts my recommendations.","Let’s showcase your business in a genuine way and elevate your brand beyond traditional advertising."],"cta":{"line":"Time to unlock your brand’s potential!","label":"Get started here"}}');
INSERT INTO content (key, value) VALUES ('reviews', '[{"quote":"We have been using her content creation services for 8 years now and we have been super impressed with the fantastic quality photography, general turn around time of services and the passion and energy put into every project and would definitely recommend their services!","name":"Keith Taeuber","org":"School of Rock Claremont"},{"quote":"She produces work that goes beyond expectations and has a passion for what she does. It is truly a pleasure to have her as a photographer.","name":"Kai Coetzee","org":"Leonista"},{"quote":"Leigh-Anne is like a breath of fresh air in any shoot environment. Always there to accommodate in any way possible, always up beat & happy, always creating. Not only is she a total professional in her work ethic, but her career is her passion, & she will not rest until she’s completely happy with the finished product. She is reliable & always punctual, & you know that you can rely on her to always deliver what is expected in the end. I recommend her highly.","name":"Paula Kelley","org":"Left of Center"},{"quote":"I have never met a more talented or dedicated photographer. Not only worth the money but she is willing to tailor the shoot and experience to you! She takes the time to get to know you as an artist and knows how to capture your essence. You will never be disappointed.","name":"Stardust Productions","org":""}]');
INSERT INTO content (key, value) VALUES ('contact', '{"phone":"+27 72 227 7016","phoneHref":"tel:+27722277016","email":"discoverwithleigh@gmail.com","studio":"Century City, Cape Town, South Africa","whatsapp":"http://wa.link/s5hdey"}');
INSERT INTO gallery (r2_key, categories, sort, w, h) VALUES ('gallery/Copy-of-IMG_9486-1024x683.jpg', '["property"]', 0, 1024, 683);
INSERT INTO gallery (r2_key, categories, sort, w, h) VALUES ('gallery/Copy-of-98342967_3489472717747515_7897782599156760576_o.jpg', '["weddings"]', 1, 875, 584);
INSERT INTO gallery (r2_key, categories, sort, w, h) VALUES ('gallery/Copy-of-PRODUCT-Drink-Leonista--768x1024.jpg', '["product"]', 2, 768, 1024);
INSERT INTO gallery (r2_key, categories, sort, w, h) VALUES ('gallery/PORTRAIT-SECTION-5-1024x1024.jpg', '["portraits"]', 3, 1024, 1024);
INSERT INTO gallery (r2_key, categories, sort, w, h) VALUES ('gallery/Copy-of-IMG_3406-1024x683.jpg', '["property"]', 4, 1024, 683);
INSERT INTO gallery (r2_key, categories, sort, w, h) VALUES ('gallery/Copy-of-_MG_9577-683x1024.jpg', '["weddings"]', 5, 683, 1024);
INSERT INTO gallery (r2_key, categories, sort, w, h) VALUES ('gallery/Copy-of-IMG_3571-1024x683.jpg', '["property"]', 6, 1024, 683);
INSERT INTO gallery (r2_key, categories, sort, w, h) VALUES ('gallery/Copy-of-IMG_9425-1024x683.jpg', '["weddings"]', 7, 1024, 683);
INSERT INTO gallery (r2_key, categories, sort, w, h) VALUES ('gallery/Copy-of-PRODUCT-Drink-Leonista-Reposado-black-1024x819.jpg', '["product"]', 8, 1024, 819);
INSERT INTO gallery (r2_key, categories, sort, w, h) VALUES ('gallery/Copy-of-PRODUCT-Food-Linkos-Sushi--768x1024.jpg', '["product"]', 9, 768, 1024);
INSERT INTO gallery (r2_key, categories, sort, w, h) VALUES ('gallery/Copy-of-232DF52B-B466-4477-8BF2-18B045F16B74.jpg', '["property"]', 10, 763, 953);
INSERT INTO gallery (r2_key, categories, sort, w, h) VALUES ('gallery/Copy-of-PRODUCT-Leonista-Blanco-1-768x1024.jpg', '["product"]', 11, 768, 1024);
INSERT INTO gallery (r2_key, categories, sort, w, h) VALUES ('gallery/PORTRAIT-SECTION-6.jpg', '["portraits"]', 12, 1000, 667);
INSERT INTO gallery (r2_key, categories, sort, w, h) VALUES ('gallery/IMG_3522-1024x683.jpg', '["property"]', 13, 1024, 683);
INSERT INTO gallery (r2_key, categories, sort, w, h) VALUES ('gallery/PORTRAIT-SECTION-2-683x1024.jpg', '["portraits"]', 14, 683, 1024);
INSERT INTO gallery (r2_key, categories, sort, w, h) VALUES ('gallery/Copy-of-PRODUCT-Drink-Glenfiddich-1024x683.jpg', '["lifestyle"]', 15, 1024, 683);
INSERT INTO gallery (r2_key, categories, sort, w, h) VALUES ('gallery/Copy-of-IMG_1337-1024x683.jpg', '["lifestyle"]', 16, 1024, 683);
INSERT INTO gallery (r2_key, categories, sort, w, h) VALUES ('gallery/MG_7850-1024x640.jpg', '["lifestyle"]', 17, 1024, 640);
INSERT INTO gallery (r2_key, categories, sort, w, h) VALUES ('gallery/Copy-of-DSC_9341-1024x683.jpg', '["weddings"]', 18, 1024, 683);
INSERT INTO gallery (r2_key, categories, sort, w, h) VALUES ('gallery/Copy-of-IMG_4207-1024x682.jpg', '["live music"]', 19, 1024, 682);
INSERT INTO gallery (r2_key, categories, sort, w, h) VALUES ('gallery/PORTRAIT-SECTION-1-683x1024.jpg', '["portraits"]', 20, 683, 1024);
INSERT INTO gallery (r2_key, categories, sort, w, h) VALUES ('gallery/PRODUCT-SECTION-2-576x1024.jpg', '["product"]', 21, 576, 1024);
INSERT INTO gallery (r2_key, categories, sort, w, h) VALUES ('gallery/Copy-of-IMG_5197-1024x683.jpg', '["live music"]', 22, 1024, 683);
INSERT INTO gallery (r2_key, categories, sort, w, h) VALUES ('gallery/Copy-of-_MG_5747-1024x683.jpg', '["property"]', 23, 1024, 683);
INSERT INTO gallery (r2_key, categories, sort, w, h) VALUES ('gallery/PORTRAIT-SECTION-3-683x1024.jpg', '["portraits"]', 24, 683, 1024);
INSERT INTO gallery (r2_key, categories, sort, w, h) VALUES ('gallery/PORTRAIT-SECTION-4-1024x1024.jpg', '["portraits"]', 25, 1024, 1024);
INSERT INTO gallery (r2_key, categories, sort, w, h) VALUES ('gallery/Copy-of-IMG_8039-Ann-Jangle.jpg', '["live music"]', 26, 1020, 680);
INSERT INTO gallery (r2_key, categories, sort, w, h) VALUES ('gallery/Copy-of-IMG_3886-1024x683.jpg', '["lifestyle"]', 27, 1024, 683);
INSERT INTO gallery (r2_key, categories, sort, w, h) VALUES ('gallery/MG_2913.jpg', '["live music"]', 28, 1000, 672);
INSERT INTO gallery (r2_key, categories, sort, w, h) VALUES ('gallery/CC-SPORT-FESTIVAL-2023-Discover-with-Leigh-13-1-683x1024.jpg', '["lifestyle"]', 29, 683, 1024);
INSERT INTO gallery (r2_key, categories, sort, w, h) VALUES ('gallery/PORTRAIT-SECTION-8-678x1024.jpg', '["portraits"]', 30, 678, 1024);
INSERT INTO gallery (r2_key, categories, sort, w, h) VALUES ('gallery/PRODUCT-Beer-Woodstock-Brewery-1-1024x683.jpg', '["lifestyle"]', 31, 1024, 683);
INSERT INTO gallery (r2_key, categories, sort, w, h) VALUES ('gallery/Copy-of-CC-SPORT-FESTIVAL-2023-Discover-with-Leigh-154-683x1024.jpg', '["lifestyle"]', 32, 683, 1024);
INSERT INTO gallery (r2_key, categories, sort, w, h) VALUES ('gallery/MG_3565-1024x683.jpg', '["live music"]', 33, 1024, 683);
INSERT INTO gallery (r2_key, categories, sort, w, h) VALUES ('gallery/MG_0518-1024x683.jpg', '["live music"]', 34, 1024, 683);
INSERT INTO gallery (r2_key, categories, sort, w, h) VALUES ('gallery/Untitled-design.png', '["product"]', 35, 1000, 1000);
INSERT INTO gallery (r2_key, categories, sort, w, h) VALUES ('gallery/MG_2605.jpg', '["live music"]', 36, 1000, 931);
INSERT INTO gallery (r2_key, categories, sort, w, h) VALUES ('gallery/Copy-of-IMG_4925-1024x683.jpg', '["live music"]', 37, 1024, 683);
INSERT INTO gallery (r2_key, categories, sort, w, h) VALUES ('gallery/Copy-of-_MG_8570-1-1024x889.jpg', '["lifestyle"]', 38, 1024, 889);
INSERT INTO gallery (r2_key, categories, sort, w, h) VALUES ('gallery/Copy-of-IMG_3387-1024x683.jpg', '["property"]', 39, 1024, 683);
INSERT INTO gallery (r2_key, categories, sort, w, h) VALUES ('gallery/CPT-SHOW-_HIGH-RES82-1024x683.jpg', '["product"]', 40, 1024, 683);
INSERT INTO gallery (r2_key, categories, sort, w, h) VALUES ('gallery/PRODUCT-SECTION-576x1024.jpg', '["product"]', 41, 576, 1024);
INSERT INTO gallery (r2_key, categories, sort, w, h) VALUES ('gallery/IMG_1631-761x1024.jpg', '["product"]', 42, 761, 1024);
INSERT INTO gallery (r2_key, categories, sort, w, h) VALUES ('gallery/Untitled-design-27-724x1024.jpg', '["weddings"]', 43, 724, 1024);
INSERT INTO gallery (r2_key, categories, sort, w, h) VALUES ('gallery/Copy-of-98338316_3489468684414585_4036918303577341952_o-1024x683.jpg', '["weddings"]', 44, 1024, 683);
INSERT INTO gallery (r2_key, categories, sort, w, h) VALUES ('gallery/Copy-of-IMG_9541-1024x683.jpg', '["weddings"]', 45, 1024, 683);
INSERT INTO gallery (r2_key, categories, sort, w, h) VALUES ('gallery/IMG_9481-1024x683.jpg', '[]', 46, 1024, 683);
INSERT INTO gallery (r2_key, categories, sort, w, h) VALUES ('gallery/IMG_1627-782x1024.jpg', '["product"]', 47, 782, 1024);
INSERT INTO gallery (r2_key, categories, sort, w, h) VALUES ('gallery/IMG_1677-881x1024.jpg', '["product"]', 48, 881, 1024);
INSERT INTO gallery (r2_key, categories, sort, w, h) VALUES ('gallery/100476267_3489468124414641_6882444629505998848_o-1024x683.jpg', '["weddings"]', 49, 1024, 683);
INSERT INTO gallery (r2_key, categories, sort, w, h) VALUES ('gallery/Copy-of-IMG_3612-1024x683.jpg', '["property"]', 50, 1024, 683);
INSERT INTO gallery (r2_key, categories, sort, w, h) VALUES ('gallery/IMG_1570-801x1024.jpg', '["product"]', 51, 801, 1024);
INSERT INTO gallery (r2_key, categories, sort, w, h) VALUES ('gallery/PORTRAIT-SECTION-7-1-1024x683.jpg', '["portraits"]', 52, 1024, 683);
INSERT INTO brands (r2_key, sort, w, h) VALUES ('brands/brand-01.png', 0, 300, 300);
INSERT INTO brands (r2_key, sort, w, h) VALUES ('brands/brand-02.png', 1, 300, 300);
INSERT INTO brands (r2_key, sort, w, h) VALUES ('brands/brand-03.png', 2, 300, 300);
INSERT INTO brands (r2_key, sort, w, h) VALUES ('brands/brand-04.png', 3, 300, 300);
INSERT INTO brands (r2_key, sort, w, h) VALUES ('brands/brand-05.png', 4, 300, 300);
INSERT INTO brands (r2_key, sort, w, h) VALUES ('brands/brand-06.png', 5, 300, 300);
INSERT INTO brands (r2_key, sort, w, h) VALUES ('brands/brand-08.png', 6, 300, 300);
INSERT INTO brands (r2_key, sort, w, h) VALUES ('brands/brand-09.png', 7, 300, 300);
INSERT INTO brands (r2_key, sort, w, h) VALUES ('brands/brand-10.png', 8, 300, 300);
INSERT INTO brands (r2_key, sort, w, h) VALUES ('brands/brand-11.png', 9, 300, 300);
INSERT INTO brands (r2_key, sort, w, h) VALUES ('brands/brand-12.png', 10, 300, 300);
INSERT INTO brands (r2_key, sort, w, h) VALUES ('brands/brand-13.png', 11, 300, 300);
INSERT INTO brands (r2_key, sort, w, h) VALUES ('brands/brand-14.png', 12, 300, 300);
INSERT INTO brands (r2_key, sort, w, h) VALUES ('brands/brand-15.png', 13, 300, 300);